seed: 1
device: 'cpu'
vae_model:
  binary_dim: 100                                                           # binary dimensionality
  depthT: 20                                                                # tree depth 
  depthG: 3                                                                 # graph depth
opt:
  output: 'results/'                      # output path
  cache: 'cache'                                                           # cache path
  surro_model: 'factorization machine'                                       # selected surrogate model
  decay_weight: 0.01                                                         # decay weight in training the surrogate model
  factor_num: 8                                                              # factorization size in the factorization machine
  maxepoch: 10000                                                            # maximum epoch in training the factorization machine
  param_init: 0.03                                                           # used for initialize parameters in FM
  lr: 0.001                                                                   # learning rate in training the factorization machine
  patience: 300                                                              # patience for unimproved epoches
  batch_size: 8                                                             # batch size in training the factorization machine
  end_cond: 0                                                                # end condition for optimization
  # 0 --> certain number of iterations; 1 --> certain number of new molecule; 2 --> exhaustion
  target: 'max'                                                              # maximize or minimize the target score
  prop: 'qed'                                                               # optimized property
  num_end: 300                                                               # number for the end condition
  n_sample: 1                                                                # number of sampled binary vectors for each molecule
  client: 'amplify'                                                          # amplify or d-wave
  client_token: ''                                          # token for connection